#!/bin/bash
sudo apt-get update -y
sudo apt-get install nginx -y
sudo touch /var/www/html/index.html
sudo chmod 777 /var/www/html/index.html
echo "Hola mundo desde la vm: $(hostname)" > /var/www/html/index.html
